"""empty message

Revision ID: 076793672295
Revises: 
Create Date: 2021-08-12 22:09:04.685744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076793672295'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('owner_idx', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('homepage', sa.String(length=32), nullable=False),
    sa.Column('callback', sa.String(length=500), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('idx')
    )
    op.create_table('application_secret',
    sa.Column('target_idx', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('target_idx')
    )
    op.create_table('code',
    sa.Column('application_idx', sa.Integer(), nullable=False),
    sa.Column('target_idx', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('application_idx')
    )
    op.create_table('history',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('is_failed', sa.Boolean(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=200), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('idx')
    )
    op.create_table('token',
    sa.Column('application_idx', sa.Integer(), nullable=False),
    sa.Column('target_idx', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('application_idx')
    )
    op.create_table('two_factor',
    sa.Column('user_idx', sa.Integer(), nullable=False),
    sa.Column('secret', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('user_idx'),
    sa.UniqueConstraint('user_idx')
    )
    op.create_table('user',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=32), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('two_factor')
    op.drop_table('token')
    op.drop_table('history')
    op.drop_table('code')
    op.drop_table('application_secret')
    op.drop_table('application')
    # ### end Alembic commands ###
