"""empty message

Revision ID: 6e473f9211a4
Revises: 161210db0bcf
Create Date: 2021-08-12 10:15:49.073091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e473f9211a4'
down_revision = '161210db0bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('delete', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'delete')
    # ### end Alembic commands ###
