"""empty message

Revision ID: fcb2b84a69e9
Revises: 169ef6950efd
Create Date: 2021-08-07 20:42:07.243453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb2b84a69e9'
down_revision = '169ef6950efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('two_factor',
    sa.Column('user_idx', sa.Integer(), nullable=False),
    sa.Column('secret', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('user_idx'),
    sa.UniqueConstraint('user_idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('two_factor')
    # ### end Alembic commands ###
